### ISSUE TITLE
[ Feat ] 로그인/회원가입/마이페이지 API 연동

### ISSUE THREAD

**Issue by pookey1104** [Growus/Econnect_yarn#14]
### 🛠 Issue

로그인/회원가입/마이페이지 API 연동

### 📝 To-do

- [x] 회원가입
- [x] 로그인
- [ ] 이메일 인증 번호 전송
- [ ] 인증 번호 확인
- [ ] 비밀번호 찾기
- [x] 마이페이지 조회
- [ ] 회원 정보 수정
- [ ] 비밀번호 변경

### 🔍 접근 방법

- `Axios`를 사용해 연동할 예정입니다~
- 서버 주소가 `http`인 점을 고려하여 iOS 보안 설정 허용 추가

- `localStorage` 대신 `Async Storage`
(🔗 참고 링크 : https://velog.io/@hojkim77/RN-ReactNativ%EC%97%90%EC%84%9C-%EA%B3%A0%EB%A0%A4%ED%95%B4%EC%95%BC%ED%95%A0-%EB%98%90-%EB%8B%A4%EB%A5%B8-%EC%A0%80%EC%9E%A5%EB%B0%A9%EC%8B%9D-Async-Storage)
- `axios`와 `RNFetchBlob` (`CORS` 이슈)
(🔗 참고 링크 : https://www.codeduthu.com/en/blog/react-native-fix-cors-by-rn-fetch-blob)
